### ISSUE TITLE
Snake speed change

### ISSUE THREAD

**Issue by wiody** [AmanAgnihotri/Snake#1]
How can i change snake speed ?

**Comment by AmanAgnihotri** [comment]
Can tweak the value of `TimeSkipPerFrame` in `Snake/Assets/Resources/DataConfig.json` to change the rate at which snake refreshes itself on screen, essentially affecting the speed of the snake.

Currently, it's set to `0.06`, which means that `0.06` seconds are skipped before every snake update. Increasing the value will slow the snake update rate thereby decreasing the snake speed, while decreasing the value would increase the snake update rate thereby increasing the snake speed.
